
export default {
BatteryID: require('./schemas/BatteryID.json'),
BatterySOH: require('./schemas/BatterySOH.json'),
Brand: require('./schemas/Brand.json'),
ContactPoint: require('./schemas/ContactPoint.json'),
Customer: require('./schemas/Customer.json'),
Entity: require('./schemas/Entity.json'),
Event: require('./schemas/Event.json'),
GeoCoordinates: require('./schemas/GeoCoordinates.json'),
Invoice: require('./schemas/Invoice.json'),
LEIaddress: require('./schemas/LEIaddress.json'),
LEIauthority: require('./schemas/LEIauthority.json'),
LEIentity: require('./schemas/LEIentity.json'),
LEIevidenceDocument: require('./schemas/LEIevidenceDocument.json'),
LEIregistration: require('./schemas/LEIregistration.json'),
LegalEntityIdentifierCredential: require('./schemas/LegalEntityIdentifierCredential.json'),
LinkRole: require('./schemas/LinkRole.json'),
Organization: require('./schemas/Organization.json'),
Person: require('./schemas/Person.json'),
Place: require('./schemas/Place.json'),
PostalAddress: require('./schemas/PostalAddress.json'),
PriceSpecification: require('./schemas/PriceSpecification.json'),
Product: require('./schemas/Product.json'),
ProductRegistrationEvidenceDocument: require('./schemas/ProductRegistrationEvidenceDocument.json'),
Purchase: require('./schemas/Purchase.json'),
QuantitativeValue: require('./schemas/QuantitativeValue.json'),
TotalCharge: require('./schemas/TotalCharge.json'),
VID: require('./schemas/VID.json'),
chargeAndPaymentType: require('./schemas/chargeAndPaymentType.json'),
}
